# providers = ["node"] # Usually auto-detected if package.json is present

[phases.setup]
nixPkgs = ["nodejs_18"] # Or your preferred stable Node.js version (e.g., nodejs_20)

[phases.build]
cmds = ["chmod +x ./railway-unified-build.sh && ./railway-unified-build.sh"]

[start]
command = "node server.js" # This starts your Express server
# healthcheckPath = "/" # Optional: Add a health check endpoint to server.js if desired
# healthcheckTimeout = "300s"