# nixpacks.toml (Minimal version to override default install)

[phases.install]
# This command will be run by Nixpacks during its 'install' phase, BEFORE the buildCommand in railway.toml.
# We ensure optional dependencies are skipped and only production dependencies are installed.
cmds = [
  "echo 'DEBUG: Custom Nixpacks install phase (nixpacks.toml)'",
  "echo 'DEBUG: Listing files in /app to check for .npmrc:'",
  "ls -la /app",
  "echo 'DEBUG: Contents of /app/.npmrc (if it exists):'",
  "cat /app/.npmrc || echo 'DEBUG: /app/.npmrc not found'",
  "echo 'DEBUG: Setting npm config optional=false directly'",
  "npm config set optional false",
  "echo 'DEBUG: Verifying npm config optional setting:'",
  "npm config get optional",
  "echo 'DEBUG: Attempting npm ci --omit=dev --omit=optional'",
  "npm ci --omit=dev --omit=optional"
]

# No other phases (like build or start) need to be defined here,
# as they are handled by railway.toml's buildCommand and startCommand.
