# nixpacks.toml

[phases.install]
# This command will be run by Nixpacks during its 'install' phase.
# We're using a simple echo command to prevent the default 'npm ci' from running.
# The actual installation will be handled by railway-unified-build.sh.
cmds = ["echo 'Skipping default Nixpacks install phase. Dependencies will be installed in railway-unified-build.sh.'"]

# The 'build' and 'start' phases are defined by railway.toml's buildCommand and startCommand.
