# nixpacks.toml

[phases.setup]
  nixPkgs = ["nodejs_20"] # Use Node.js 20

# railway-unified-build.sh handles all npm installs.

[phases.build]
  cmds = ["chmod +x ./railway-unified-build.sh && ./railway-unified-build.sh"]

[start]
  command = "node server.js" # Starts your Express server

[variables]
  NODE_ENV = "production"
  NIXPACKS_NODE_VERSION = "20" # Explicitly set Node version for Nixpacks