# nixpacks.toml
# This file is now minimal. The primary dependency installation logic
# has been moved to railway-unified-build.sh to ensure it runs after
# Nixpacks copies all project files into the build environment.

[phases.install]
# Override Nixpacks default install command (which would be 'npm ci' due to presence of package-lock.json).
# We want to defer all dependency installation to railway-unified-build.sh.
cmds = [
  "echo 'Nixpacks default install phase overridden. Dependency installation will be handled by railway-unified-build.sh.'"
]

# The 'build' and 'start' phases are defined by railway.toml's buildCommand and startCommand.
