# nixpacks.toml

[phases.setup]
# Only include absolutely essential build dependencies
pkgs = ["nodejs"]

[phases.install]
# Skip the default npm install, we'll handle it in railway-unified-build.sh
cmds = [
  "echo 'Skipping default Nixpacks install phase. Dependencies will be installed in railway-unified-build.sh.'"
]

# Optimize the build process
[phases.build]
# Run our custom build script
cmds = [
  "chmod +x ./railway-unified-build.sh",
  "chmod +x ./railway-start.sh",
  "./railway-unified-build.sh"
]

# Define the start command
[phases.start]
cmds = ["./railway-start.sh"]
