# nixpacks.toml for Flex Plugin

[phases.setup]
  nixPkgs = ["nodejs_20"]  # Use Node.js 20

[phases.install]
  cmds = [
    "echo 'Installing system dependencies...'",
    # Install any system dependencies if needed
  ]

[phases.build]
  cmds = [
    "echo 'Starting build process...'",
    "chmod +x ./railway-build.sh",
    "./railway-build.sh"
  ]

# Start command for Railway
[start]
  command = "node server.js"

# Health check configuration for Railway
[healthcheck]
  path = "/"
  initial_delay = "10s"
  interval = "30s"
  timeout = "10s"

# Environment variables
[variables]
  NODE_ENV = "production"
  NIXPACKS_NODE_VERSION = "20"
  NODE_OPTIONS = "--max-old-space-size=1024 --no-warnings"
  PORT = "3000"
  
  # Twilio configuration
  TWILIO_ACCOUNT_SID = "${TWILIO_ACCOUNT_SID}"
  TWILIO_AUTH_TOKEN = "${TWILIO_AUTH_TOKEN:-4320eb2a6d58faef9c9c21a8f13aa3e3}"
  
  # Flex plugin environment
  TWILIO_FLEX_PLUGIN_ENV = "production"
  
  # Required for some Twilio Flex plugins
  REACT_APP_FLEX_APP_URL = "/"
  
[build.args]
  # Ensure we have enough memory for the build
  NODE_OPTIONS = "--max-old-space-size=2048"

[build.ignore]
  # Ignore unnecessary files to speed up builds
  ignore = [
    "node_modules",
    ".git",
    ".github",
    ".vscode",
    "coverage",
    "dist",
    "build",
    "*.log"
  ]
